In [1]:
import numpy as np
import pandas as pd
import os

lista = []
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        lista.append(os.path.join(dirname, filename))

In [ ]:
dfs = [pd.read_csv(item) for item in lista]
df = pd.concat(dfs)

In [3]:
df = df[['Year', 'Script Type', 'Rotten Tomatoes  critics', 
    'Metacritic  critics', 'Average audience ', 'Worldwide Gross ($million)',
   'Budget ($million)', 'Primary Genre']]

In [4]:
df.isna().sum()

Year                             0
Script Type                    193
Rotten Tomatoes  critics         1
Metacritic  critics              0
Average audience                 1
Worldwide Gross ($million)       0
Budget ($million)                0
Primary Genre                 1689
dtype: int64

In [5]:
col = df.columns.get_loc('Script Type')

df['Script Type'] = df['Script Type'].fillna('unknown')
for i in range(len(df)):
    value = df.iloc[i, col]

    if 'original' in value:
        value = 'original'
    elif 'sequel' in value:
        value = 'sequel'
    elif 'true story' in value or 'documentary' in value:
        value = 'real'
    elif 'adaptation' in value:
        value = 'adaptation'
    elif 'remake'in value:
        value = 'remake'
    elif 'prequel' in value:
        value = 'prequel'
    else:
        value = 'unknown'
    
    df.iloc[i, col] = value

df['Script Type'].unique()

array(['unknown', 'original', 'sequel', 'adaptation', 'real', 'remake',
       'prequel'], dtype=object)

In [6]:
coluna = 'Rotten Tomatoes  critics'
df = df[df[coluna] != '-']
df[coluna].dropna(inplace=True)
df[coluna] = pd.to_numeric(df[coluna])
df[coluna].unique()

array([  0.,  96.,  69.,  32.,  75.,  57.,  92.,  68.,  39.,  84.,  85.,
        82.,  81.,  88.,  53.,  63.,  80.,  73.,  62.,  74.,  77.,  38.,
        86.,  44.,  94.,  95.,  79.,  40.,  46.,  41.,  11.,  72.,  55.,
        29.,  23.,  98.,  61.,  70.,  36.,  15.,  54.,  93.,  17.,  76.,
        87.,  71.,  91.,  24.,  83.,  21.,  89.,  64.,  35.,  50.,  42.,
        18.,  60.,  14.,  51.,  66.,  97.,  78.,  45.,  19.,  25.,  47.,
        48.,  67.,  26.,  37.,  56.,  90.,  43.,  99.,  59.,  22.,  34.,
        27.,  10.,  52.,  13.,  28.,  49.,  31.,   1.,   2.,   3.,   4.,
         8.,   9.,  20.,  30.,  33.,  65.,  12.,  16.,  58.,   7.,   5.,
         6., 100.,  nan])

In [7]:
coluna = 'Metacritic  critics'
df = df[df[coluna] != '-'].copy()
df[coluna].dropna(inplace=True)
df[coluna] = pd.to_numeric(df[coluna])
df[coluna].unique()

array([ 95,  55,  48,  74,  61,  78,  54,  41,  67,  69,  66,  72,  49,
        50,  56,  52,  60,  63,  64,  75,  81,  62,  47,  40,  32,  38,
        51,  80,  35,  65,  70,  77,  45,  76,  73,  68,  92,  59,  31,
        71,  82,  57,  79,  43,  39,  30,  53,  28,  84,  46,  58,  44,
        42,  91,  83,  17,  96,  24,  25,  36,  26,  19,  37,  89,  11,
        29,  13,  33,  85,  27,  88,  94,  23,  34,  18,  93,  21,  22,
        87,  99,  86,   9,  15,  20,  14,  90,  12, 100,  16,  97])

In [8]:
coluna = 'Average audience '
df = df[df[coluna] != '-'].copy()
df[coluna] = pd.to_numeric(df[coluna])
df[coluna].dropna(inplace=True)
df[coluna].unique()

array([81. , 72. , 57. , 61. , 73. , 63. , 74. , 66. , 71. , 56. , 69. ,
       77. , 76. , 59. , 80. , 52. , 85. , 84. , 78. , 37. , 36. , 55. ,
       82. , 38. , 86. , 89. , 83. , 70. , 79. , 75. , 91. , 65. , 88. ,
       49. , 64. , 45. , 62. , 51. , 41. , 25. , 60. , 47. , 48. , 54. ,
       68. , 58. , 87. , 67. , 53. , 46. , 90. , 40. , 39. , 44. , 31. ,
       30. , 42. , 29. , 24. , 50. , 43. , 35. , 90.5, 85.5, 64.5, 77.5,
       74.5, 59.5, 79.5, 55.5, 63.5, 66.5, 48.5, 69.5, 82.5, 73.5, 58.5,
       40.5, 57.5, 41.5, 72.5, 54.5, 47.5, 62.5, 80.5, 65.5, 67.5, 70.5,
       75.5, 32.5, 56.5, 81.5, 71.5, 34. , 33.5, 76.5, 86.5, 15.5, 52.5,
       78.5, 46.5, 18.5, 60.5, 51.5, 43.5, 61.5, 93. , 22. , 28. ,  nan,
       32. , 27. , 33. , 92. , 23. ,  7. , 19. ])

In [9]:
coluna = 'Primary Genre'
df[coluna] = df[coluna].fillna('unknown')
df[coluna].value_counts()

Primary Genre
unknown      1680
action         67
drama          49
comedy         42
adventure      24
thriller       20
horror         18
crime          13
biography       8
animation       6
romance         6
musical         3
fantasy         3
western         2
sci-fi          2
mystery         1
Name: count, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Primary Genre'] = le.fit_transform(df['Primary Genre'])

le2 = LabelEncoder()
df['Script Type'] = le2.fit_transform(df['Script Type'])
df

Year  Script Type  Rotten Tomatoes  critics  Metacritic  critics  \
1    2022            6                      96.0                   95   
2    2022            6                      69.0                   55   
3    2022            6                      32.0                   48   
4    2022            6                      75.0                   74   
5    2022            6                      57.0                   61   
..    ...          ...                       ...                  ...   
96   2021            6                      25.0                   44   
97   2021            6                      92.0                   85   
98   2021            6                      67.0                   57   
99   2021            6                      65.0                   46   
100  2021            6                      88.0                   76   

     Average audience  Worldwide Gross ($million) Budget ($million)  \
1                 81.0                        7.8                 -   
2                 72.0                       51.8              40.0   
3                 57.0                       29.4              80.0   
4                 57.0                        6.6              15.0   
5                 61.0                       63.3             110.0   
..                 ...                        ...               ...   
96                53.0                        4.1              29.0   
97                82.0                       74.8             100.0   
98                80.0                      103.9              40.0   
99                52.0                        3.6                 -   
100               65.0                        5.2               5.0   

     Primary Genre  
1                6  
2               13  
3                4  
4                6  
5                4  
..             ...  
96               1  
97               9  
98               0  
99               8  
100              4  

[1944 rows x 8 columns]